<?php

return [
    [
        "name"=>"html-boolando",
        "type"=>"html",
        "image"=>""
    ],
    [
        "name"=>"html-css-boolzap",
        "type"=>"html/css",
        "image"=>""
    ],
    [
        "name"=>"html-hello",
        "type"=>"html",
        "image"=>""
    ],
    [
        "name"=>"js-array-carousel",
        "type"=>"js",
        "image"=>""
    ],
    [
        "name"=>"js-biglietto-treno",
        "type"=>"js",
        "image"=>""
    ],
    [
        "name"=>"vue-fizz-buzz",
        "type"=>"vue",
        "image"=>""
    ],
    [
        "name"=>"vue-boolzapp",
        "type"=>"vue",
        "image"=>""
    ],
    [
        "name"=>"vite-boolflix",
        "type"=>"vite",
        "image"=>""
    ],
    [
        "name"=>"vite-boolflix",
        "type"=>"vite",
        "image"=>""
    ],
    [
        "name"=>"php-dischi-json",
        "type"=>"php",
        "image"=>""
    ],
    [
        "name"=>"laravel-dc-comics",
        "type"=>"laravell",
        "image"=>""
    ],
];
