<?php

return [
    [
        "name"=>"html-boolando",
        "type"=>"html",
    ],
    [
        "name"=>"html-css-boolzap",
        "type"=>"html",
    ],
    [
        "name"=>"vite-hello",
        "type"=>"vite",
    ],
    [
        "name"=>"html-array-carousel",
        "type"=>"html",
    ],
    [
        "name"=>"vite-biglietto-treno",
        "type"=>"vite",
    ],
    [
        "name"=>"vue-fizz-buzz",
        "type"=>"vite",
    ],
    [
        "name"=>"php-boolzapp",
        "type"=>"php",
    ],
    [
        "name"=>"laravel-boolflix",
        "type"=>"laravel",
    ],
    [
        "name"=>"php-boolflix",
        "type"=>"php",
    ],
    [
        "name"=>"laravel-dischi-json",
        "type"=>"laravel",
    ],
    [
        "name"=>"laravel-dc-comics",
        "type"=>"laravel",
    ],
];
