<?php

return [
    [
        "name"=>"html-boolando",
        "type"=>"html"
    ],
    [
        "name"=>"html-css-boolzap",
        "type"=>"html/css"
    ],
    [
        "name"=>"html-hello",
        "type"=>"html"
    ],
    [
        "name"=>"js-array-carousel",
        "type"=>"js"
    ],
    [
        "name"=>"js-biglietto-treno",
        "type"=>"js"
    ],
    [
        "name"=>"vue-fizz-buzz",
        "type"=>"vue"
    ],
    [
        "name"=>"vue-boolzapp",
        "type"=>"vue"
    ],
    [
        "name"=>"vite-boolflix",
        "type"=>"vite"
    ],
    [
        "name"=>"vite-boolflix",
        "type"=>"vite"
    ],
    [
        "name"=>"php-dischi-json",
        "type"=>"php"
    ],
    [
        "name"=>"laravel-dc-comics",
        "type"=>"laravell"
    ],
];
